### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by darcyabjones** [ccdmb/slurm_scripts#1]
Hey Johannes,

We're going to try to setup some template projects given that using acacia seems to make it a bit more difficult for people.
Do you mind if I rearrange things in here a bit?

I've forked a copy to work on, but this is really the place that we should all contribute to.
As an example of what I'm doing, I've just created a wrapper for rclone/acacia (https://github.com/darcyabjones/ccdmb_slurm_scripts/blob/master/bin/rclone_batch.sh) which we can use to stage data with job dependencies really easily.

Ta,
Darcy

**Comment by JWDebler** [comment]
Sure thing, go ahead :-)
